select DEPTNO,
		SUM(if(JOB='CLERK', SAL, 0)) CLERK,
		SUM(if(JOB='SALESMAN', SAL, 0)) SALESMAN,
        SUM(if(JOB='MANAGER', SAL, 0)) MANAGER,
        SUM(if(JOB='ANALYST', SAL, 0)) ANALYST,
        SUM(if(JOB='PRESIDENT', SAL, 0)) PRESIDENT
from EMP
GROUP BY DEPTNO
ORDER BY DEPTNO;

select DEPTNO, SUM(SAL)
FROM EMP
group by DEPTNO WITH ROLLUP;

select DEPTNO, JOB, SUM(SAL)
FROM EMP
group by DEPTNO, JOB WITH ROLLUP
order by DEPTNO;